### ISSUE TITLE
Disable runit

### ISSUE THREAD

**Issue by micred** [leifcr/capistrano-puma#3]
I don't want to use runit, just monit, how can I do?
I've already add: 

    before "monit:unmonitor", "puma:monit:stop"
    after  "monit:monitor",   "puma:monit:start"

but it keeps trying to create files on shared/runit/puma and on /etc/services.

**Comment by leifcr** [comment]
This gem is made for using runit for managing the service (puma) and monit for monitoring. You cannot use one without the other in this gem. The monit setup is responsible for restarting the service if it uses too much memory, restart it if it crashes etc and alert you when stuff fail. Feel free to do a fork and a PR if you would like it to be optional.
