### ISSUE TITLE
It doesn't use sudo

### ISSUE THREAD

**Issue by micred** [leifcr/capistrano-puma#4]
It tries to create a symbolic link in /etc without using sudo.

```
ln -sf '/etc/sv/deploy/xxxxx_production' '/etc/service/deploy_xxxxx_production'
```

It highly dangerous to deploy with a root user (or a user with r/w access to /etc) so it's preferable to use sudo. Do you agree?

**Comment by leifcr** [comment]
Sudo is deprecated in Capistrano. Create a sudoers file so that the deploy user is allowed to setup symbolic links where needed.
